default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: animal-blog-app_development

test:
  <<: *default
  database: animal-blog-app_test

production:
  <<: *default
  database: animal-blog-app_production
  username: animal-blog-app
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>